### ISSUE TITLE
compiling errors

### ISSUE THREAD

**Issue by leon419** [Bntdumas/SamsungIPRemote#1]
QByteArray's function toAscii is now toLatin1

**Comment by Bntdumas** [comment]
Hi, 

Thanks for pointing this out, I just pushed a fix that should allow compilation for both Qt4 and 5

Benoit

**Comment by antoniovr** [comment]
Still getting the toAscii problem compiling with Q5.

Regards!

**Comment by Bntdumas** [comment]
Hi antoniovr,
I'll check this out, can you give me more infos on the error you get? I tried compiling the lib with Qt5 when I fixed the bug (on linux) and it worked fine.

**Comment by antoniovr** [comment]
tvNetworkControl.cpp:169: error: 'const class QString' has no member named 'toAscii'
     const QByteArray strBase64 = QByteArray(str.toAscii()).toBase64();

Line 169

First time using QT, maybe it's my fault. I'm using the latest version from http://qt-project.org/downloads (5.2)

Regards,

**Comment by Bntdumas** [comment]
Try replacing the line with:
const QByteArray strBase64 = QByteArray(str.toLatin1()).toBase64();

If it solves the problem for you I'll post an update

**Comment by antoniovr** [comment]
Yep, it works. It's weird, I thought I already tried that after reading the previous posts.

Thanks a lot for your quick response! and very nice work.

Regards,

**Comment by Bntdumas** [comment]
Just posted a fix, thank you for pointing out the error :)
